"""Canonical diagram content; shared by web interaction and SVG exports."""
from pathlib import Path
import html,json
ROOT=Path(__file__).resolve().parents[1]
DIAGRAMS=[
 {'id':'access-capability','number':'01','after':1,'default':'outcome','title':{'zh':'两股力量，相互放大','en':'Two forces, working together'},'summary':{'zh':'开源降低门槛，人的成长释放创造力；数据与评价为行动提供支撑。','en':'Open source lowers barriers; human development unlocks creativity. Data and evaluation support both.'},'note':{'zh':'“×”表达相互促进的行动框架，不是定量公式。','en':'“×” expresses mutual reinforcement, not a quantitative formula.'},'nodes':[
  {'id':'open','tag':'OPEN SOURCE','title':{'zh':['用得起'],'en':['Affordable access']},'sub':{'zh':['开放技术与知识','降低成本 · 扩大可获得性'],'en':['Open technology and knowledge','Lower costs · Wider access']},'desktop':[20,45,295,132],'mobile':[30,30,280,120],'detail':{'zh':'开放工具、知识和实践经验，降低学习与使用成本，让更多人有机会开始。开源是降低门槛的路径，仍需关注持续使用的实际成本。','en':'Open tools, knowledge and practical experience can lower the cost of learning and use. Access must also account for the real cost of sustained use.'}},
  {'id':'people','tag':'HUMAN CAPABILITY','title':{'zh':['用得好'],'en':['Capable use']},'sub':{'zh':['学习、判断与创造','从理解工具到解决问题'],'en':['Learning, judgment and creativity','From tools to real problems']},'desktop':[405,45,295,132],'mobile':[30,202,280,120],'detail':{'zh':'通过学习、协作和真实问题实践，积累技术能力与判断力。AI 支持人的思考，也需要人理解局限、检验证据并承担责任。','en':'Learning, collaboration and practice build technical skills and judgment. People still need to understand limitations, examine evidence and take responsibility.'}},
  {'id':'outcome','tag':'AI FOR ALL','title':{'zh':['AI 普惠'],'en':['AI for All']},'sub':{'zh':['更多人能够获取、掌握并创造'],'en':['More people can access, learn and create']},'desktop':[160,255,400,92],'mobile':[30,380,280,104],'detail':{'zh':'目标是扩大人的选择与实际能力。技术可获得性与人的成长需要共同推进；成效由真实学习、创造和处境改善来检验。','en':'The goal is greater choice and capability. Access and human development must advance together; results are tested through learning, creation and better circumstances.'}},
  {'id':'support','tag':'SUPPORTING METHOD','title':{'zh':['数据与评价'],'en':['Data and evaluation']},'sub':{'zh':['让贡献可见 · 让行动可检验'],'en':['Make contributions visible · Examine outcomes']},'desktop':[90,415,540,90],'mobile':[30,549,280,112],'detail':{'zh':'数据与评价服务于贡献识别、资源配置和效果检验。它们是支撑方法，不替代人的判断，也不以单一分数定义人的价值。','en':'Data and evaluation support recognition, resource allocation and examination of outcomes. They do not replace human judgment or define a person’s worth by one score.'}}
 ],'edges':{'desktop':[('open','outcome','M167.5 177 V213 H360 V247',False),('people','outcome','M552.5 177 V213 H360',False),('support','outcome','M360 415 V355',True)],'mobile':[('open','outcome','M310 90 H325 V360 H170 V372',False),('people','outcome','M170 322 V372',False),('support','outcome','M170 549 V492',True)]},'height':{'desktop':535,'mobile':690},'labels':{'desktop':[(360,121,'×','×',32),(386,385,'支撑','Support',14)],'mobile':[(170,180,'×','×',28),(195,523,'支撑','Support',14)]}},
 {'id':'path-to-benefit','number':'02','after':2,'default':'benefit','title':{'zh':'从开发者出发，让价值抵达更多人','en':'From developers to wider public benefit'},'summary':{'zh':'开发者成长，经由真实应用走向更广泛受益，并接受需求与反馈的检验。','en':'Developer growth reaches more people through useful applications, guided by needs and feedback.'},'note':{'zh':'这是需要实践验证的路径，不是自动发生的因果关系。','en':'A path to test in practice—not an automatic causal chain.'},'nodes':[
  {'id':'developers','tag':'01 / DEVELOP','title':{'zh':['开发者成长'],'en':['Developer','growth']},'sub':{'zh':['学习 · 构建 · 协作'],'en':['Learn · Build · Collaborate']},'desktop':[20,55,200,140],'mobile':[30,30,280,120],'detail':{'zh':'从正在学习、构建工具和解决问题的人出发。初学者也应有进入的机会；代码、文档、教学和社区协作都可以创造价值。','en':'Begin with people learning, building tools and solving problems. Beginners need an entry point, and code, documentation, teaching and collaboration can all create value.'}},
  {'id':'applications','tag':'02 / APPLY','title':{'zh':['真实应用'],'en':['Useful','applications']},'sub':{'zh':['回应具体问题'],'en':['Address real needs']},'desktop':[260,55,200,140],'mobile':[30,199,280,120],'detail':{'zh':'将能力转化为工具、服务和知识，回应具体场景中的需要。关注是否容易理解、负担和使用，而不只关注技术是否先进。','en':'Turn capability into tools, services and knowledge for real needs. Ask whether people can understand, afford and use them, not only whether the technology is advanced.'}},
  {'id':'benefit','tag':'03 / BENEFIT','title':{'zh':['更广泛受益'],'en':['Wider public','benefit']},'sub':{'zh':['学习 · 创造 · 处境改善'],'en':['Learning · Creating','Better lives']},'desktop':[500,55,200,140],'mobile':[30,368,280,120],'detail':{'zh':'检查谁实际获得帮助、发生了什么变化，以及哪些人仍未被覆盖。关注资源不足的人群与地区，并与当地伙伴共同理解使用条件。','en':'Examine who benefits, what changes and who is still excluded. Attend to people and regions with fewer resources and understand local conditions with local partners.'}},
  {'id':'feedback','tag':'LISTEN & LEARN','title':{'zh':['需求与反馈'],'en':['Needs and feedback']},'sub':{'zh':['让真实使用反过来改善供给'],'en':['Let real use improve what we build']},'desktop':[180,292,360,102],'mobile':[30,537,280,112],'detail':{'zh':'把使用者的困难、经验和不同意见带回学习与创造。开发者数量、项目数量或工具触达，都不能单独代替公众受益的证据。','en':'Bring users’ difficulties, experience and disagreements back into learning and creation. Developer counts, project counts and reach alone are not evidence of public benefit.'}}
 ],'edges':{'desktop':[('developers','applications','M220 125 H252',False),('applications','benefit','M460 125 H492',False),('benefit','feedback','M600 195 V343 H548',False),('feedback','developers','M180 343 H120 V203',True)],'mobile':[('developers','applications','M170 150 V191',False),('applications','benefit','M170 319 V360',False),('benefit','feedback','M170 488 V529',False),('feedback','developers','M30 593 H12 V90 H22',True)]},'height':{'desktop':435,'mobile':680},'labels':{'desktop':[(360,239,'受益需要被验证','Benefit must be demonstrated',14)],'mobile':[]}},
 {'id':'learning-loop','number':'03','after':3,'default':'boundaries','title':{'zh':'让实践，持续检验承诺','en':'Let practice test the promise'},'summary':{'zh':'行动、观察、评价与改进形成循环；多元贡献、知情选择和纠错贯穿全程。','en':'Act, observe, evaluate and improve, with diverse contributions, informed choice and correction throughout.'},'note':{'zh':'评价帮助人和社区成长，不制造新的门槛。','en':'Evaluation should support growth, not create new barriers.'},'nodes':[
  {'id':'act','tag':'01 / ACT','title':{'zh':['行动实践'],'en':['Put plans into practice']},'sub':{'zh':['明确对象、条件与支持边界'],'en':['Clarify goals, conditions and limits']},'desktop':[20,40,295,112],'mobile':[30,30,280,115],'detail':{'zh':'从清晰的服务对象与真实问题开始，说明参与条件、实际资源和责任人。区分计划、试点与已完成事项，不把愿望写成成果。','en':'Start with clear participants and real problems. Explain conditions, available resources and responsibilities, and distinguish plans, pilots and completed work.'}},
  {'id':'observe','tag':'02 / OBSERVE','title':{'zh':['观察变化'],'en':['Observe what changes']},'sub':{'zh':['结合证据与参与者反馈'],'en':['Evidence and participant feedback']},'desktop':[405,40,295,112],'mobile':[30,194,280,115],'detail':{'zh':'记录谁获得了什么帮助、遇到了哪些困难。把实际交付、使用变化和参与者反馈放在一起理解，并尊重个人数据选择。','en':'Record who received what help and what difficulties remain. Interpret delivery, changes in use and participant feedback together, respecting choices about personal data.'}},
  {'id':'evaluate','tag':'03 / EVALUATE','title':{'zh':['评价与反思'],'en':['Evaluate and reflect']},'sub':{'zh':['识别效果、局限与遗漏'],'en':['Identify effects, limits and gaps']},'desktop':[405,267,295,112],'mobile':[30,358,280,115],'detail':{'zh':'解释评价方法及其局限，检查行动是否回应需求、是否遗漏特定人群。用多种证据形成判断，不把可测量的活动等同于全部价值。','en':'Explain methods and limitations, assess whether needs are met and identify excluded groups. Use varied evidence rather than equating measurable activity with all value.'}},
  {'id':'improve','tag':'04 / IMPROVE','title':{'zh':['调整与改进'],'en':['Adjust and improve']},'sub':{'zh':['修正方法、支持与下一步行动'],'en':['Revise methods, support and next steps']},'desktop':[20,267,295,112],'mobile':[30,522,280,115],'detail':{'zh':'依据证据与反馈调整行动和资源支持。说明未能兑现的承诺与原因，公开改进记录，再进入下一轮实践。','en':'Adjust actions and support using evidence and feedback. Explain unmet commitments and their causes, record improvements and begin the next cycle.'}},
  {'id':'boundaries','tag':'THROUGHOUT THE CYCLE','title':{'zh':['贯穿全程的边界'],'en':['Commitments throughout']},'sub':{'zh':['多元贡献 · 知情选择 · 纠错改进'],'en':['Diverse contributions · Informed choice · Correction']},'desktop':[20,443,680,96],'mobile':[30,705,280,123],'detail':{'zh':'尊重不同形式的贡献，不以单一分数定义人；尊重数据使用的知情与选择；允许质疑、纠错和持续改进。评价始终服务于人的成长。','en':'Respect varied contributions and do not reduce people to a score. Support informed data choices and allow questions, corrections and improvement. Evaluation serves human development.'}}
 ],'edges':{'desktop':[('act','observe','M315 96 H397',False),('observe','evaluate','M552.5 152 V259',False),('evaluate','improve','M405 323 H323',False),('improve','act','M167.5 267 V160',False)],'mobile':[('act','observe','M170 145 V186',False),('observe','evaluate','M170 309 V350',False),('evaluate','improve','M170 473 V514',False),('improve','act','M30 580 H12 V87 H22',False)]},'height':{'desktop':568,'mobile':857},'labels':{'desktop':[(360,212,'公开记录 · 持续学习','Open records · Continuous learning',14)],'mobile':[(170,673,'公开记录 · 持续学习','Open records · Keep learning',13)]}}
]
def e(s):return html.escape(str(s),quote=True)
def svg(d,lang,mobile=False,export=False):
 mode='mobile' if mobile else 'desktop';w=340 if mobile else 720;h=d['height'][mode];prefix=d['id']+'-'+lang+'-'+mode
 offset=105 if export else 0;total=h+offset+(78 if export else 0)
 out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {total}" width="{w}" height="{total}" class="concept-svg" aria-hidden="true">' if not export else f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {total}" width="{w}" height="{total}" role="img" aria-labelledby="title desc">',f'<title id="{("title" if export else prefix+"-title")}">{e(d["title"][lang])}</title><desc id="{("desc" if export else prefix+"-desc")}">{e(d["summary"][lang])}</desc>',f'<defs><marker id="{prefix}-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L6 3.5 L0 7" fill="none" stroke="#78928a" stroke-width="1.2"/></marker></defs>', '<rect width="100%" height="100%" fill="#ffffff"/>']
 if export:
  out+=[f'<text x="20" y="29" font-family="Arial,sans-serif" font-size="11" letter-spacing="2" fill="#56746a">X-LAB AI / AI FOR ALL / {d["number"]}</text>',f'<text x="20" y="64" font-family="Arial, Noto Sans CJK SC, Source Han Sans SC, sans-serif" font-size="25" font-weight="600" fill="#112d22">{e(d["title"][lang])}</text>',f'<path d="M20 86 H700" fill="none" stroke="#dbe5df"/>']
 out.append(f'<g transform="translate(0,{offset})">')
 for fr,to,path,dashed in d['edges'][mode]:
  out.append(f'<path class="concept-edge" data-from="{fr}" data-to="{to}" d="{path}" fill="none" stroke="#8ba299" stroke-width="1.4"'+('' if d["id"]=="access-capability" and fr=="people" and not mobile else f' marker-end="url(#{prefix}-arrow)"')+(' stroke-dasharray="5 5"' if dashed else '')+'/>')
 for x,y,zh,en,size in d['labels'][mode]:out.append(f'<text x="{x}" y="{y}" font-family="Arial, Noto Sans CJK SC, Source Han Sans SC, sans-serif" text-anchor="middle" font-size="{size}" fill="#647c70">{e(zh if lang=="zh" else en)}</text>')
 for n in d['nodes']:
  x,y,nw,nh=n[mode];isout=n['id']=='outcome';support=n['id'] in ['support','boundaries'];stroke='#63943d' if isout else '#9aafa4';fill='#f3f9ee' if isout else '#f8faf9' if support else '#fff'
  out.append(f'<g class="concept-node" data-node="{n["id"]}"><rect x="{x}" y="{y}" width="{nw}" height="{nh}" rx="5" fill="{fill}" stroke="{stroke}" stroke-width="1.2"/>')
  out.append(f'<text x="{x+nw/2}" y="{y+22}" font-family="Arial,sans-serif" text-anchor="middle" font-size="9.5" letter-spacing="1.1" fill="#5a7867">{e(n["tag"])}</text>')
  title=n['title'][lang];subs=n['sub'][lang];fs=22 if lang=='zh' else 18
  if mobile and n['id']=='boundaries' and lang=='en':subs=['Diverse contributions · Informed choice','Questions, corrections and improvement']
  if mobile and n['id']=='outcome' and lang=='en':subs=['More people can access,','learn and create']
  if mobile and n['id']=='support' and lang=='en':subs=['Make contributions visible','Examine outcomes']
  ty=y+48
  for line in title:
   out.append(f'<text x="{x+nw/2}" y="{ty}" font-family="Arial, Noto Sans CJK SC, Source Han Sans SC, sans-serif" font-size="{fs}" font-weight="600" text-anchor="middle" fill="#153126">{e(line)}</text>');ty+=25
  sy=ty+1
  for line in subs:
   out.append(f'<text x="{x+nw/2}" y="{sy}" font-family="Arial, Noto Sans CJK SC, Source Han Sans SC, sans-serif" font-size="{13 if lang=="en" else 14}" text-anchor="middle" fill="#536c5f">{e(line)}</text>');sy+=20
  out.append('</g>')
 out.append('</g>')
 if export:
  out.append(f'<path d="M20 {total-66} H700" fill="none" stroke="#dbe5df"/><text x="20" y="{total-38}" font-family="Arial, Noto Sans CJK SC, Source Han Sans SC, sans-serif" font-size="13" fill="#526e61">{e(d["note"][lang])}</text><text x="20" y="{total-15}" font-family="Arial,sans-serif" font-size="10" letter-spacing=".5" fill="#789185">www.x-lab.info/ai-for-all/</text>')
 out.append('</svg>');return '\n'.join(out)
def figure(d,lang):
 hint='点选框内节点，查看它在行动中的含义。' if lang=='zh' else 'Select a box to explore its role in the action.'
 out=[f'<figure class="concept" id="{d["id"]}" aria-labelledby="{d["id"]}-heading"><figcaption><span class="concept-index">FIG. {d["number"]}</span><h3 id="{d["id"]}-heading">{e(d["title"][lang])}</h3></figcaption><p class="concept-hint">{hint}</p>']
 for mobile in [False,True]:
  mode='mobile' if mobile else 'desktop';w=340 if mobile else 720
  out.append(f'<div class="concept-canvas concept-{mode}">{svg(d,lang,mobile)}<div class="concept-controls" role="group" aria-label="{e(d["title"][lang])}">')
  for n in d['nodes']:
   x,y,nw,nh=n[mode];style=f'left:{100*x/w:.5f}%;top:{100*y/d["height"][mode]:.5f}%;width:{100*nw/w:.5f}%;height:{100*nh/d["height"][mode]:.5f}%'
   out.append(f'<button type="button" class="concept-hit" data-select="{n["id"]}" style="{style}" aria-pressed="false" aria-controls="{d["id"]}-detail"><span class="visually-hidden">{e(" · ".join(n["title"][lang]))}</span></button>')
  out.append('</div></div>')
 default=next(n for n in d['nodes'] if n['id']==d['default'])
 out.append(f'<div class="concept-detail" id="{d["id"]}-detail" role="status" aria-live="polite" aria-atomic="true"><strong>{e(" · ".join(default["title"][lang]))}</strong><p>{e(default["detail"][lang])}</p></div>')
 out.append('<div class="concept-foot"><span>'+e(d['note'][lang])+'</span><a href="assets/diagrams/'+d['id']+'-'+lang+'.svg" download>'+('下载 SVG' if lang=='zh' else 'Download SVG')+'</a><a href="assets/diagrams/'+d['id']+'-'+lang+'.png" download>'+('下载 PNG' if lang=='zh' else 'Download PNG')+'</a></div>')
 out.append('<script type="application/json" class="concept-data">'+json.dumps({n['id']:{'title':' · '.join(n['title'][lang]),'detail':n['detail'][lang]} for n in d['nodes']},ensure_ascii=False).replace('</',r'<\/')+'</script></figure>')
 return '\n'.join(out)
def export_all():
 dst=ROOT/'site/assets/diagrams';dst.mkdir(parents=True,exist_ok=True)
 for d in DIAGRAMS:
  for lang in ['zh','en']:(dst/(d['id']+'-'+lang+'.svg')).write_text(svg(d,lang,export=True))
if __name__=='__main__':export_all()
